In [3]:
import numpy as np

def simplex(of,basis,tableau,opt):
    # Get the number of rows and columns in the tableau:
    n_rows = tableau.shape[0]
    n_cols = tableau.shape[1]
    if opt =='MIN':
        # Start the simplex algorithm:
        # Compute zj-cj. If cj - zj >= 0 for all columns then current 
        # solution is optimal solution.
        check = of - np.sum(np.reshape(of[list(basis)],(n_rows,1)) * tableau[:,0:n_cols-1],axis=0)
    else:
        # Start the simplex algorithm:
        # Compute cj-zj. If zj - cj >= 0 for all columns then current
        # solution is optimal solution.
        check = np.sum(np.reshape(of[list(basis)],(n_rows,1)) *tableau[:,0:n_cols-1],axis=0) - of
    count = 0
    while ~np.all(check >=0):
        print(check)
        # Determine the pivot column:
        # The pivot column is the column corresponding to 
        # minimum zj-cj.
        pivot_col = np.argmin(check)
        # Determine the positive elements in the pivot column.
        # If there are no positive elements in the pivot column  
        # then the optimal solution is unbounded.
        positive_rows = np.where(tableau[:,pivot_col] > 0)[0]
        if positive_rows.size == 0:
            print('Unbounded Solution!')
            break
        # Determine the pivot row:
        #min-ration test
        divide=(tableau[positive_rows,n_cols-1]
            /tableau[positive_rows,pivot_col])
        pivot_row = positive_rows[np.where(divide 
            == divide.min())[0][-1]]
        # Update the basis:
        basis[pivot_row] = pivot_col
        # Perform gaussian elimination to make pivot element one and
        # elements above and below it zero:
        tableau[pivot_row,:]=(tableau[pivot_row,:]
            /tableau[pivot_row,pivot_col])
        for row in range(n_rows):
            if row != pivot_row:
                tableau[row,:] = (tableau[row,:] 
                    - tableau[row,pivot_col]*tableau[pivot_row,:])
        if opt =='MIN':
            check = of - np.sum(np.reshape(of[list(basis)],(n_rows,1)) * tableau[:,0:n_cols-1],axis=0)
        else:
            check = np.sum(np.reshape(of[list(basis)],(n_rows,1)) *tableau[:,0:n_cols-1],axis=0) - of
        count += 1
        print('Step %d' % count)
        print(tableau)
    return basis,tableau

def get_solution(of,basis,tableau):
    # Get the no of columns in the tableau:
    n_cols = tableau.shape[1]
    # Get the optimal solution:
    solution = np.zeros(of.size)
    solution[list(basis)] = tableau[:,n_cols-1]
    # Determine the optimal value:
    value = np.sum(of[list(basis)] * tableau[:,n_cols-1])
    return solution,value

Solve the following L.P.P. by Simplex Method.

Maximize $z=4x_1+5x_2+9x_3+11x_4$ subject to
$$
\begin{aligned}
x_1+x_2+x_3+x_4 &\leq 15,  \\
7x_1 + 5x_2+3x_3+2x_4 &\leq 120, \\
3x_1+5x_2+10x_3+15x_4 &\leq 100, \\
x_1,x_2,x_3,x_4 &\geq 0
\end{aligned}
$$

### Solution

We can convert the problem into the standard form by adding slack variables $x_5,x_6$ and $x_7$. 

Maximize $z = 4x_1+5x_2+9x_3+11x_4+0x_5+0x_6+0x_7$ subject to
$$\begin{aligned}
x_1+x_2+x_3+x_4+x_5 &= 15, \\
7x_1+5x_2+3x_3+2x_4 +x_6 &= 120, \\
3x_1+5x_2+10x_3+15x_4+x_7 &= 100, \\
x_1,x_2,x_3,x_4,x_5,x_6,x_7 &\geq 0
\end{aligned}$$

We are now ready to solve the problem.

In [5]:
def question1():
    # Define the tableau:
    tableau = np.array([
        [1.0,1,1,1,1,0,0,15],
        [7,5,3,2,0,1,0,120],
        [3,5,10,15,0,0,1,100]
    ])
    # Define the objective function and the initial basis:
    of = np.array([4,5,9,11,0,0,0])
    #initial basis
    basis = np.array([4,5,6])
    # Run the simplex algorithm:
    basis,tableau = simplex(of,basis,tableau,'MAX')
    # Get the optimal soultion:
    optimal_solution,optimal_value = get_solution(of,basis,tableau)
    # Print the final tableau:
    print('The final basis is:')
    print(basis)
    print('solution')
    for i in range(len(optimal_solution)):
        print('X%d'%(i+1),'=',optimal_solution[i])
    print('Z=',optimal_value)
question1()

[ -4.  -5.  -9. -11.   0.   0.   0.]
Step 1
[[ 8.00000000e-01  6.66666667e-01  3.33333333e-01  0.00000000e+00
   1.00000000e+00  0.00000000e+00 -6.66666667e-02  8.33333333e+00]
 [ 6.60000000e+00  4.33333333e+00  1.66666667e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00 -1.33333333e-01  1.06666667e+02]
 [ 2.00000000e-01  3.33333333e-01  6.66666667e-01  1.00000000e+00
   0.00000000e+00  0.00000000e+00  6.66666667e-02  6.66666667e+00]]
[-1.8        -1.33333333 -1.66666667  0.          0.          0.
  0.73333333]
Step 2
[[ 1.          0.83333333  0.41666667  0.          1.25        0.
  -0.08333333 10.41666667]
 [ 0.         -1.16666667 -1.08333333  0.         -8.25        1.
   0.41666667 37.91666667]
 [ 0.          0.16666667  0.58333333  1.         -0.25        0.
   0.08333333  4.58333333]]
[ 0.          0.16666667 -0.91666667  0.          2.25        0.
  0.58333333]
Step 3
[[ 1.          0.71428571  0.         -0.71428571  1.42857143  0.
  -0.14285714  7.14285714]
 [ 0.      

In [6]:
def question2():
    # Define the tableau:
    tableau = np.array([
        [3.0,-1,2,1,0,0,7],
        [-1,-4,0,0,1,0,12],
        [-4,3,8,0,0,1,10]
    ])
    # Define the objective function and the initial basis:
    of = np.array([1,-3,3,0,0,0])
    #initial basis
    basis = np.array([3,4,5])
    # Run the simplex algorithm:
    basis,tableau = simplex(of,basis,tableau,'MIN')
    # Get the optimal soultion:
    optimal_solution,optimal_value = get_solution(of,basis,tableau)
    # Print the final tableau:
    print('The final basis is:')
    print(basis)
    print('solution')
    for i in range(len(optimal_solution)):
        print('X%d'%(i+1),'=',optimal_solution[i])
    print('Z=',optimal_value)
question2()

[ 1. -3.  3.  0.  0.  0.]
Step 1
[[ 1.66666667  0.          4.66666667  1.          0.          0.33333333
  10.33333333]
 [-6.33333333  0.         10.66666667  0.          1.          1.33333333
  25.33333333]
 [-1.33333333  1.          2.66666667  0.          0.          0.33333333
   3.33333333]]
[-3.  0. 11.  0.  0.  1.]
Step 2
[[ 1.   0.   2.8  0.6  0.   0.2  6.2]
 [ 0.   0.  28.4  3.8  1.   2.6 64.6]
 [ 0.   1.   6.4  0.8  0.   0.6 11.6]]
The final basis is:
[0 4 1]
solution
X1 = 6.2
X2 = 11.6
X3 = 0.0
X4 = 0.0
X5 = 64.6
X6 = 0.0
Z= -28.599999999999998
